In [3]:
import numpy as np

## Numpy arrays

In [5]:
a = [1,4,7,-4,-10]

In [13]:
type(a)

list

In [27]:
type(a[0])

int

In [31]:
arr = np.array(a)

In [33]:
type(arr)

numpy.ndarray

In [35]:
type(arr[0])

numpy.int32

In [37]:
arr2 = np.array(a, dtype = float)

In [39]:
type(arr2)

numpy.ndarray

In [41]:
type(arr2[0])

numpy.float64

In [44]:
arr3 = np.array(arr)

In [46]:
type(arr3)

numpy.ndarray

In [48]:
type(arr3[0])

numpy.int32

## Part 1

### to convert to array:

In [51]:
arr4 = np.array(a)

### reverse NumPy array 

In [54]:
arr4[::-1]

array([-10,  -4,   7,   4,   1])

### shape

The shape tool gives a tuple of array dimensions and can be used to change the dimensions of an array.

In [57]:
arr4.shape

(5,)

5 rows and 1 column

In [62]:
arr4.shape = (1,5)

In [64]:
arr4

array([[  1,   4,   7,  -4, -10]])

In [66]:
arr4.shape

(1, 5)

1 row 5 column

### reshape

The reshape tool gives a new shape to an array without changing its data. It creates a new array and does not modify the original array itself.

In [69]:
arr5 = np.array(a)

In [81]:
# np.reshape(arr5,(3,2))
a = [1,2,4,6,12,45]

 total number of elements in the array should match the number of elements required by the new shape.

In [85]:
arr = np.array(a)

In [87]:
np.reshape(arr, (3,2))

array([[ 1,  2],
       [ 4,  6],
       [12, 45]])

In [89]:
np.reshape(arr, (2,3))

array([[ 1,  2,  4],
       [ 6, 12, 45]])

### Transpose 

In [94]:
arr

array([ 1,  2,  4,  6, 12, 45])

In [96]:
arr.T

array([ 1,  2,  4,  6, 12, 45])

In [106]:
np.transpose(arr)

array([ 1,  2,  4,  6, 12, 45])

In [108]:
reshaped_arr = np.reshape(arr, (3,2))

In [110]:
reshaped_arr

array([[ 1,  2],
       [ 4,  6],
       [12, 45]])

In [112]:
reshaped_arr.T

array([[ 1,  4, 12],
       [ 2,  6, 45]])

In [114]:
reshaped_arr.transpose

<function ndarray.transpose>

In [116]:
np.transpose(reshaped_arr)

array([[ 1,  4, 12],
       [ 2,  6, 45]])

### Flatten

In [123]:
arr.flatten()

array([ 1,  2,  4,  6, 12, 45])

In [130]:
reshaped_arr

array([[ 1,  2],
       [ 4,  6],
       [12, 45]])

In [127]:
reshaped_arr.flatten()

array([ 1,  2,  4,  6, 12, 45])

In [132]:
type(reshaped_arr)

numpy.ndarray

In [134]:
reshaped_arr.shape

(3, 2)

In [136]:
reshaped_arr.flatten().shape

(6,)

## Part 2

In [141]:
import numpy

array_1 = numpy.array([1,2,3])
array_2 = numpy.array([4,5,6])
array_3 = numpy.array([7,8,9])

### Concatenate

In [146]:
np.concatenate([array_1, array_2, array_3])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Correct usage, passing arrays inside a list or tuple

In [151]:
arr1 = np.array([[1,2,3],[0,0,0]])
arr2 = np.array([[0,0,0],[4,5,6]])

In [153]:
arr1

array([[1, 2, 3],
       [0, 0, 0]])

In [155]:
arr2

array([[0, 0, 0],
       [4, 5, 6]])

In [159]:
print(arr1)

[[1 2 3]
 [0 0 0]]


In [161]:
print(arr2)

[[0 0 0]
 [4 5 6]]


In [167]:
arr1.shape

(2, 3)

In [169]:
type(arr1)

numpy.ndarray

In [175]:
np.concatenate([arr1, arr2]) # axis = 0 by default across rows

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0],
       [4, 5, 6]])

In [179]:
np.concatenate([arr1, arr2], axis = 1) # stack across columns

array([[1, 2, 3, 0, 0, 0],
       [0, 0, 0, 4, 5, 6]])

### zeros and ones

In [189]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [191]:
np.zeros(5, int)

array([0, 0, 0, 0, 0])

In [193]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [195]:
np.zeros((3,6), int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [197]:
np.ones

<function numpy.ones(shape, dtype=None, order='C', *, like=None)>

In [199]:
np.ones(1)

array([1.])

In [201]:
np.ones(2, int)

array([1, 1])

In [203]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [205]:
np.ones((2,3), int)

array([[1, 1, 1],
       [1, 1, 1]])

### identity

The identity tool returns an identity array. An identity array is a square matrix with all the main diagonal elements as  and the rest as .

In [208]:
np.identity

<function numpy.identity(n, dtype=None, *, like=None)>

In [210]:
np.identity(1)

array([[1.]])

In [212]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### eye

The eye tool returns a 2-D array with 1's as the diagonal and 0's elsewhere. The diagonal can be main, upper or lower depending on the optional parameter k

In [222]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [224]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [230]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [232]:
np.eye(3,k=2)

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [234]:
np.eye(3,k=3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [236]:
np.eye(5,4,k=0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [240]:
np.eye(5,4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [242]:
np.eye(5,4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [244]:
np.eye(5,4,k=-4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [248]:
np.eye(5,4,k=3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### array maths

In [252]:
a = np.array([1,2,3,4])
b = np.array([5,3,4,6])

In [254]:
a+b

array([ 6,  5,  7, 10])

In [256]:
a-b

array([-4, -1, -1, -2])

In [258]:
a*b

array([ 5,  6, 12, 24])

In [260]:
a/b

array([0.2       , 0.66666667, 0.75      , 0.66666667])

In [262]:
a%b

array([1, 2, 3, 4])

In [264]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [266]:
b%2

array([1, 1, 0, 0], dtype=int32)

In [268]:
a**b

array([   1,    8,   81, 4096])

In [270]:
a = np.array([1,2,3,4,3])
b = np.array([5,3,4,6])

#a+b

ValueError: operands could not be broadcast together with shapes (5,) (4,) 


In [275]:
a1 = [1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8]

In [279]:
np.floor(a1)

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [281]:
np.ceil(a1)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [283]:
np.round(a1)

array([1., 2., 3., 4., 6., 7., 8., 9.])

#### rint
The rint tool rounds to the nearest integer of input element-wise.

In [286]:
np.rint(a1)

array([1., 2., 3., 4., 6., 7., 8., 9.])

### sum and product

In [341]:
a = np.array([1,2,3])

In [343]:
b = np.array([4,5,6])

In [345]:
print(a)

[1 2 3]


In [347]:
print(b)

[4 5 6]


In [349]:
np.concatenate([a,b], axis = 0)

array([1, 2, 3, 4, 5, 6])

**column wise**

In [352]:
a_reshaped = a.reshape(-1, 1)  # shape (3, 1)
b_reshaped = b.reshape(-1, 1)  # shape (3, 1)

In [354]:
np.concatenate([a_reshaped,b_reshaped], axis = 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [356]:
np.concatenate([a_reshaped,b_reshaped], axis = 0)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

**row wise**

In [359]:
a_reshaped = a.reshape(1, -1)  # shape (1, 3)
b_reshaped = b.reshape(1, -1)  # shape (1, 3)

In [361]:
np.concatenate([a_reshaped,b_reshaped], axis = 1)

array([[1, 2, 3, 4, 5, 6]])

In [363]:
np.concatenate([a_reshaped,b_reshaped], axis = 0)

array([[1, 2, 3],
       [4, 5, 6]])

## Part 3

In [368]:
a = [1,2,3]
b = [5,6,2]
c = [1, 0, 10]

In [372]:
arr1 = np.array(a)
arr2 = np.array(b)
arr3 = np.array(c)

In [378]:
print(arr2)

[5 6 2]


In [382]:
arr1.shape

(3,)

In [388]:
mat = np.array([a,b,c])

In [391]:
mat

array([[ 1,  2,  3],
       [ 5,  6,  2],
       [ 1,  0, 10]])

In [393]:
mat.shape

(3, 3)

In [411]:
mat2 = np.array([arr1,arr2,arr3])

In [415]:
mat2

array([[ 1,  2,  3],
       [ 5,  6,  2],
       [ 1,  0, 10]])

In [418]:
mat2.shape

(3, 3)

In [424]:
mat3 = np.concatenate([arr1.reshape(-1,1),arr2.reshape(-1,1)], axis = 1)

In [426]:
mat3

array([[1, 5],
       [2, 6],
       [3, 2]])

In [428]:
mat4 = np.concatenate([arr1.reshape(1,-1),arr2.reshape(1,-1)], axis = 0)

In [430]:
mat4

array([[1, 2, 3],
       [5, 6, 2]])

### prod

The prod tool returns the product of array elements over a given axis.

In [433]:
np.prod(mat)

0

In [439]:
np.prod(mat, axis = 1)

array([ 6, 60,  0])

In [441]:
row_prod = np.prod(mat, axis = 1)

In [443]:
row_prod

array([ 6, 60,  0])

In [449]:
print(row_prod)

[ 6 60  0]


In [445]:
row_prod.size

3

In [447]:
row_prod.shape

(3,)

In [451]:
row_prod.reshape(-1,1)

array([[ 6],
       [60],
       [ 0]])

In [455]:
np.prod(mat, axis = 0)

array([ 5,  0, 60])

In [457]:
col_prod = np.prod(mat, axis = 0)

In [459]:
col_prod

array([ 5,  0, 60])

In [461]:
col_prod.shape

(3,)

In [463]:
col_prod.reshape(1,-1)

array([[ 5,  0, 60]])

In [469]:
mat3

array([[1, 5],
       [2, 6],
       [3, 2]])

In [465]:
np.prod(mat3)

360

In [475]:
mat4

array([[1, 2, 3],
       [5, 6, 2]])

In [467]:
np.prod(mat4)

360

In [471]:
np.prod(mat4, axis = 0)

array([ 5, 12,  6])

In [489]:
mat4

array([[1, 2, 3],
       [5, 6, 2]])

In [487]:
col_prod = np.prod(mat4, axis = 0)
col_prod.reshape(1,-1)

array([[ 5, 12,  6]])

In [510]:
row_prod = np.prod(mat4, axis = 1)
row_prod.reshape(-1,1)

array([[ 6],
       [60]])

same for sum

### min and max

In [492]:
mat4

array([[1, 2, 3],
       [5, 6, 2]])

In [494]:
np.min(mat4)

1

In [502]:
np.min(mat4, axis = 0) # across columns

array([1, 2, 2])

In [507]:
np.min(mat4, axis = 1).reshape(-1,1) # across rows, showing in 1 column

array([[1],
       [2]])

same for max

### mean, var, std

In [514]:
mat4

array([[1, 2, 3],
       [5, 6, 2]])

In [516]:
np.mean(mat4)

3.1666666666666665

In [518]:
np.var(mat4)

3.138888888888889

In [520]:
np.std(mat4)

1.7716909687891083

#### row wsie (horizontally) | across columns

In [525]:
np.mean(mat4, axis = 1).reshape(-1,1)

array([[2.        ],
       [4.33333333]])

In [527]:
np.var(mat4, axis = 1).reshape(-1,1)

array([[0.66666667],
       [2.88888889]])

In [531]:
np.std(mat4, axis = 1).reshape(-1,1)

array([[0.81649658],
       [1.69967317]])

#### column wise (vertically) | across rows
**by default most things operate vertically | axis = 0 | "across rows going vertically down, column wise**""

In [534]:
np.mean(mat4, axis = 0)

array([3. , 4. , 2.5])

In [538]:
np.mean(mat4)

3.1666666666666665

In [546]:
np.var(mat4, axis = 0)

array([4.  , 4.  , 0.25])

In [548]:
np.std(mat4, axis =0)

array([2. , 2. , 0.5])

## Part 4

### dot and cross

In [566]:
arr1 = np.array([1,2,3])
arr2 = np.array([6,3,5])

In [568]:
type(arr1)

numpy.ndarray

In [570]:
arr1.shape

(3,)

In [572]:
arr1.dot(arr2)

27

In [578]:
np.dot(arr1,arr2)

27

In [580]:
np.cross(arr1,arr2)

array([ 1, 13, -9])

### inner and outer

inner = dot

In [586]:
np.inner(arr1,arr2)

27

outer = col vector * row vector

In [588]:
np.outer(arr1,arr2)

array([[ 6,  3,  5],
       [12,  6, 10],
       [18,  9, 15]])

In [590]:
col_v = arr1.reshape(-1,1)

In [592]:
col_v

array([[1],
       [2],
       [3]])

In [594]:
row_v = arr2.reshape(1,-1)

In [596]:
row_v

array([[6, 3, 5]])

In [602]:
col_v*(row_v)

array([[ 6,  3,  5],
       [12,  6, 10],
       [18,  9, 15]])

**finish**